### ISSUE TITLE
Register implementation

### ISSUE THREAD

**Issue by KasonBraley** [Chat-LI/Chat-LI-Client#11]
Implement a way for a client to register an account after launching the application in the terminal. Once the account is created on the backend, it should then back an appropriate socket event and login the user.

- [x] Prompt: give user two choices: 1. Register 2. Login
- [x] accept a username and password in the prompt
- [x] `base64.encode()` the username:password
- [x] emit a `register` event to the backend
- [x] listen for a `registered` event from the backend
- [x] use proper error handling

**Comment by Beers15** [comment]
Issue resolved
