### ISSUE TITLE
Login Implementation

### ISSUE THREAD

**Issue by KasonBraley** [Chat-LI/Chat-LI-Client#13]
Implement a way for a client to login to an account after launching the application in the terminal. If the user has already registered for an account, they should be able to login to that account. 

- [x] Prompt: give user two choices: 1. Register 2. Login
- [x] accept a username and password in the prompt
- [x] base64.encode() the username:password
- [x] emit a `login` event to the backend
- [x] listen for a `logged-in` event from the backend
- [x] use the user's created username as their chat handle instead of the socket id
- [x] use proper error handling

**Comment by Beers15** [comment]
Issue resolved: used REST actions i.o. socket events for login

**Comment by Beers15** [comment]
"emit a login event to the backend"
"listen for a logged-in event from the backend"

Does not apply @KasonBraley
